### ISSUE TITLE
Missing more detailed info

### ISSUE THREAD

**Issue by BaltasarParreira** [SurrealityLabs/xmas-icetube-wifi#1]
Sorry but I can't understand what this WIFI PCB really do as it lacks detailed information.
How this connects to the Xmas Icetube Clock board, thought the GPS points?
What about the code running inside the ESP board, where can we find it?

**Comment by rglenn** [comment]
Sorry, documentation and code aren't available yet. One day I'll get around to finishing this project, but it's likely going to be a few months from now.

**Comment by BaltasarParreira** [comment]
Never mind and thanks anyway, but I figure out looking to the PCB on Kicad that this is just a pin breakout PCB for a ESP stamp version so we can have a sort of Nodemcu board.

Regarding the code I already did your work myself.   ; )

It works on any ESP board and generates NMEA spoof/fake messages on serial port so the Icetube clock thinks that as a GPS connected, you can read all about it and find the code here:
[NTP to GPS for Icetube clock using any ESP8266 or ESP32](https://github.com/johngarchie/xmas-icetube/issues/12)
